### ISSUE TITLE
(De)associating routes to an outing without GPS data

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1006]
How is georef handled?
When I create an outing without GPS data, it looks like a location is registered ( @asaunier based on what? main summit of first route?). Although the waypoints of the route are not displayed in the outing map (I assume there is another issue or discussion about this), we see there is a georef.
When associating another route or removing one, nothing changes. Shouldn't it recompute the georef (if it's only a point) with the same logic as when the outing is created?

(I know this may have been discussed somewhere else, sorry for the inconvenience)

**Comment by asaunier** [comment]
> When I create an outing without GPS data, it looks like a location is registered ( @asaunier based on what? main summit of first route?).

I don't remember exactly. @tsauerwein better knows.
If the new outing has no geometry (uploaded GPX or track drawn on the map) a default point geometry is retrieved from the associated route (don't know what happens when there are several associated routes).
Same thing for routes: if no geometry is explicitly provided, the main WP geometry is used as the default route point geometry.

> Although the waypoints of the route are not displayed in the outing map

No surprise becase no WP is associated to an outing. Associated WP are only shown in route maps. Actually that's the same behaviour than in v5.

> When associating another route or removing one, nothing changes. Shouldn't it recompute the georef (if it's only a point) with the same logic as when the outing is created?

I don't know.

**Comment by asaunier** [comment]
@stef74 has tagged this issue "Go Live". But is there really something to do?

**Comment by brunobesson** [comment]
I think so. The main point of my issue was

>When associating another route or removing one, nothing changes. Shouldn't it recompute the georef (if it's only a point) with the same logic as when the outing is created?

Currently, it's not possible to edit the geometry of an outing, either by uploading a new GPX file or drawing on the map.

**Comment by stef74** [comment]
@brunobesson You open dedicated issue and close your question ?

**Comment by brunobesson** [comment]
Created issue #1056 instead.
