### ISSUE TITLE
Images search date filter do not work

### ISSUE THREAD

**Issue by dkocich** [c2corg/v6_ui#1054]
* [ ] Image count is not updated and list remains same after selection of any date.

![image](https://cloud.githubusercontent.com/assets/6165660/20787894/7fa8bb14-b7ae-11e6-9c61-4d2e034a21bf.png)

**Comment by asaunier** [comment]
In addition
* [ ] The date picker is cut:
![sans titre](https://cloud.githubusercontent.com/assets/1192331/20788358/c62904e8-b7b0-11e6-8cb1-c0c2d4e27a10.png)

**Comment by ginold** [comment]
^ the same problem as stated in #655 -> it only happens when you scroll down and open a menu, not happening if you are on the top of the list.

**Comment by asaunier** [comment]
> Image count is not updated and list remains same after selection of any date.

Selecting a date does not even update the filter parameters in the URL, thus not trigger the search either.

That's because the date filter in the images search page:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/image/filters.html#L41
use a ``filtersCtrl.setDate()`` function that is only available for outings:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/search/outingfilters.js#L89
not in the standard search controller used for images:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/search/searchfilters.js

To add the date support we should create a extended fitler controller for images (as for outings) with a ``setDate`` function (or factorize it to the parent controller but it's not really a common function needed by all document types).

Question: do we really need a date filter for images? If not, I would recommend to simply remove this filter. Has anyone already complained about it?

**Comment by asaunier** [comment]
> Question: do we really need a date filter for images? If not, I would recommend to simply remove this filter. Has anyone already complained about it?

@desnoes Has the association given some feedbacks about this question? Is the issue still relevant?

**Comment by desnoes** [comment]
According to the discussion in the forum, this functionality is not really necessary. You can remove the filter.
