### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#1114]
WP:
- [x] button "Add a new route to this waypoint"

**Comment by asaunier** [comment]
This string should be translated in Transifex. @desnoes has done it this afternoon:

**Comment by loicperrin** [comment]
OK. I have not found it as "to be translated", so I thought that it did not exist in Transifex.

Another one (already translated for 3 months):
- [ ] when I try to create a new account, I get an english message beginning with "Registration failed:"

**Comment by asaunier** [comment]
> I have not found it as "to be translated", so I thought that it did not exist in Transifex.

Simply type (a part of) the string in the search engine of Transifex.

> I try to create a new account, I get an english message beginning with "Registration failed:"

This string also exists in Transifex. It's the same problem than for "Login failed", see https://github.com/c2corg/v6_ui/issues/1041
and the suggested fix: https://github.com/c2corg/v6_ui/pull/1111

Since this problem is related to https://github.com/c2corg/v6_ui/issues/1041 it's more or less a duplicate, I prefer closing it again :)
