### ISSUE TITLE
Image slideshow is "moody"

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#1117]
Going forward and backward in the image slideshow does not work properly. When clicking on the next arrow, the next image flashes up, but then the current image is shown again.

**Comment by fbunoz** [comment]
I see also this behavior, which is a bit random : sometime it's work correctly, sometime not.

More over, on desktop it would be better that a click on a large part of right or left image goes to the next/perv image, instead of clicking only on the small arrow. the keyboard arrow work also, but sometime we use the keyboard, or the mouse.

**Comment by tsauerwein** [comment]
> More over, on desktop it would be better that a click on a large part of right or left image goes to the next/perv image, instead of clicking only on the small arrow. the keyboard arrow work also, but sometime we use the keyboard, or the mouse.

Please open a separate issue for that.

**Comment by asaunier** [comment]
> More over, on desktop it would be better that a click on a large part of right or left image goes to the next/perv image, instead of clicking only on the small arrow. the keyboard arrow work also, but sometime we use the keyboard, or the mouse.

Please note it is possible to drag the image with the mouse cursor to the right or to the left. It's 2016, people no longer click, they drag :P
