### ISSUE TITLE
Books section

### ISSUE THREAD

**Issue by lbesson** [c2corg/v6_ui#1161]
Suggestion (I could work on it but would like feedback first :p)

Having the books as cards is quite difficult to read, and takes a lot of place. Would it be good to put it in the left info pane?

I know this breaks the general way to display linked docs, but IMHO this would improve the readability

**Comment by stef74** [comment]
Could you provide example or mokup ?

**Comment by stef74** [comment]
Laster = to be define ... if you work on it add "association"

**Comment by asaunier** [comment]
IMO, your suggestion is not going into the right directions.

All document links should be shown as cards. It's not consistent to have cards for some types and normal links for other.
It should be automatic in people's mind: cards=documents.
In addition cards are needed for mobile usage.

There are a few cases where cards are not used: users associated to an outing, regions...
But it was in my plans that one day they will be listed as cards as well.

Perhaps the problem is that cards are too big, perhaps with too many info.
I think we should rather work on card sizes and content. Perhaps also on where they are shown.

**Comment by lbesson** [comment]
I understand the principle, but to be honest, as it is right now, the
"linked books" section is just completely unreadable to me :)

**Comment by asaunier** [comment]
Could you give an example?

**Comment by lbesson** [comment]
https://www.camptocamp.org/routes/53874/fr/la-meije-grand-pic-arete-du-promontoire-voie-normale-puis-traversee-des-aretes

Cards are huge, with very few displayed information very useful (who really
cares about the book activity, whose icons take a lot of space? Even the
book type is superfluous in that context) A picture of the book instead
would be far more useful (but I know that displaying _the_ book cover is
not easy technically)

**Comment by asaunier** [comment]
OK thanks.
That's what I said: probably the content of the cards and the size of the cards are not optimal.
I think we should work on this, not changing the concept of cards.
