### ISSUE TITLE
URL are lost if there is no word linked to an URL

### ISSUE THREAD

**Issue by HSERGERAERT** [c2corg/v6_ui#1166]
Example https://www.camptocamp.org/outings/820562/fr/sainte-baume-pic-de-bertagne-baou-de-bartagne-voie-de-la-romaine
You can see a hyperlink associated to "mon site".
Il the original outing on v5, the "mon site" wasn't there, in the outing the sentence was ""plus d'infos sur: http://sud-ascension.com/topo-bartagne/"
As there was no word in between the balise (in>out), then the link now disappears, it displays on v6 "plus d'infos sur:".
The user asks if it will be solved, or if he has to change every outing to set back a correct link.
Thanks to keep him aware :

**Comment by asaunier** [comment]
Hervé, we are not responsible for contacting every individual. It's the association task. Not the SA's.
I have removed this user's email address because I am not sure he is OK that it's made public (at least for spam reasons).

This is a migration problem. It should have been reported before the golive. The association has failed detecting it in the demo during the test period.
Now it's too late.

**Comment by asaunier** [comment]
But I am a bit surprised because I don't think we have made changes on tag such as ``[url]``. Perhaps this document was already like this in v5?
Do we really have the problem in every document containing ``[url]`` tags?

**Comment by asaunier** [comment]
@brunobesson OK thanks for the tip, you're probably right.

Instead of changing the data, perhaps it's possible to adapt or extend the BBcode parser so that this syntax is supported to.
https://github.com/dcwatson/bbcode
http://bbcode.readthedocs.io/en/latest/

**Comment by HSERGERAERT** [comment]
I thought my initial explaination was clear enough, it wasn't :(
Thanks Bruno.
Answer made to the user. I close the ticket
