### ISSUE TITLE
Syncer needs to be more verbose and recover automatically from error conditions

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1169]
See https://forum.camptocamp.org/t/le-point-lac-destom-napparait-pas-en-recherche-ni-dans-le-topoguide/173500/3 and https://www.camptocamp.org/waypoints/829217/fr/lac-d-estom.

**Comment by asaunier** [comment]
Probably related to redis disponibility problems observed those time and preventing the ES index syncer from doing its job.

**Comment by brunobesson** [comment]
Is there an action to be done on your side?

**Comment by mgerbaux** [comment]
In the same idea ?
On https://www.camptocamp.org/outings , last outings that appears where created 8th of december, whereas recenter exist ( thehttps://www.camptocamp.org/outings/830058/fr/l-oreille-du-loup-goulotte-zia ).

**Comment by mfournier** [comment]
I've checked the syncer process' logs, and there seems to not have been a single log line emitted since shortly after the latest outing appearing on the outings list (latest outing at this point: is https://www.camptocamp.org/outings/history/829169/it). This is also a short moment before the first redis crash we suffered, so possibly related.

Whatever, I restarted the syncer process, and after a few minutes the latests outings seem to appear at the above address again.

See this dashboard: https://c2corgv6.logs.camptocamp.net/kibana/#dashboard/temp/AVjvdh3477AJgFSik5fD
This is all we know about this event, so I'm afraid we won't be able to do much about it this time.

As the cause of the "Newly created waypoint doesn't appear on waypoints map nor in search" is identified, I'm renaming this issue so it describes the work to be done better.
