### ISSUE TITLE
Missing URL attribute is not reported when editing a weather station or webcam

### ISSUE THREAD

**Issue by lbesson** [c2corg/v6_ui#1178]
I tried to change "[Balise nivose de Bonnepierre](https://www.camptocamp.org/waypoints/130274/fr/balise-nivose-de-bonnepierre)" to meteo station type, but I'm unable to validate the edition  and the UI doesn't explicit what prevents the submission

**Comment by asaunier** [comment]
> the UI doesn't explicit what prevents the submission

Indeed, the "save" button is disabled because some missing attribute is not set. Usually clicking on the button gives a tip with the missing attribute but I have not been able to make it work.
Looking at the fields with an asterisk, I have figured out that the URL attribute was mandatory but not set.
I have set it to http://metaskirando.camptocamp.org/Nivo.php#Ecr as in the description and then it was possible to validate the change.

**Comment by desnoes** [comment]
> Indeed, the "save" button is disabled because some missing attribute is not set. Usually clicking on the button gives a tip with the missing attribute but I have not been able to make it work.
Looking at the fields with an asterisk, I have figured out that the URL attribute was mandatory but not set.
I have set it to http://metaskirando.camptocamp.org/Nivo.php#Ecr as in the description and then it was possible to validate the change.
*
I have reported this issue in #1126

**Comment by asaunier** [comment]
@desnoes @brunobesson I think this issue is already fixed in prod: when creating a weather station or a webcam with no URL or no valid URL, the "save" button is disabled, clicking on it actually warn that the URL attribute is expected.

**Comment by asaunier** [comment]
@desnoes @brunobesson @lbesson Don't you think this issue is fixed and could be closed?

**Comment by desnoes** [comment]
@asaunier: you are right. I closed the issue.
