### ISSUE TITLE
Wrong field title for height in image pages

### ISSUE THREAD

**Issue by lbesson** [c2corg/v6_ui#1181]
Field says "elevation" instead of "height"

![2016-12-10](https://cloud.githubusercontent.com/assets/127776/21073796/c88e326e-bee8-11e6-91aa-1dce78bf3bef.png)

**Comment by lbesson** [comment]
the height key is translated by ~elevation but in that case it is the image height

either we should introduce a new key, or if height is used only in that context, change the translation in all languages

**Comment by lbesson** [comment]
According to transifex this is used in image pages and in filters for climbing sites. In both cases "hauteur" would be more appropriate, so I would suggest to update the translations in all languages accordingly

**Comment by lbesson** [comment]
Any way there might be some confusions on other places between altitude and height, see for example https://www.camptocamp.org/waypoints/808947/fr/annot-offwidth-paradise "Altitude min/max" is probably wrong. Also the "height" filter should be checked

**Comment by asaunier** [comment]
It's a translation error in Transifex, isn't it?
``height`` should be translated to ``hauteur``, not ``altitude``.

Not sure github issues are the right place to report translation errors since most translators don't use github. In addition I have the feeling it pollutes "dev" issues and make the report system harder to use.

Isn't there a ticketing system in Transifex? I know it's possible to make a comment or problem report on a given translation. Not sure it is shown for all lang versions of the string. To be confirmed.

**Comment by asaunier** [comment]
"height" was initially translated to "Hauteur" but @fbunoz has changed it to "Altitude" (?) 2 months ago. I have reverted to "Hauteur" in Transifex.
