### ISSUE TITLE
GPX track in outing can be clicked

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1193]
And when clicking, it opens... the outing page. The track should not be selectable/clickable.

**Comment by asaunier** [comment]
What's the problem of having the track clickable?
At least it's a consistent behaviour: any object shown on the map can be clicked and it will open the detail view of this object. Pretty useful for WP associated to the current route. Ditto for routes associated to the current WP (even though we have finally decided not to show them on the map because at that time, route geometries were not simplified enough).
I think it is not worth complicated the code to introduce special cases and recommend to close the issue.

**Comment by brunobesson** [comment]
The problem is minor but what's the interest of it? I am on a outing page, I click a "link" and all it does is opening the page again. It's useless and in some cases a design issue (imagine you want to scroll in the map but inadvertently simply click the track).
But I do agree this is minor.

**Comment by brunobesson** [comment]
Let's close this.
