### ISSUE TITLE
Route search: display error with 'matériel glacier'

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1252]
Route search (activity : Neige galce et mixte): the field associated to 'matériel glacier' are not dispalyed correctly (Chrome).
![bug matos glacier](https://cloud.githubusercontent.com/assets/19892089/21420302/3e277a74-c82d-11e6-8074-fe3ee7f96480.jpg)

**Comment by ginold** [comment]
I will close this issue and report this problem in #655

**Comment by fjacon** [comment]
It looks like it is working now.

Can we close this ?

**Comment by asaunier** [comment]
> It looks like it is working now.

It seems not, including with the new layout (but there no change about the filters panel I think):
https://www.demov6.camptocamp.org/routes#bbox=-803425%252C3535588%252C1603424%252C7664411&act=skitouring
![capture du 2017-11-02 16-49-23](https://user-images.githubusercontent.com/1192331/32335730-d303fb82-bfed-11e7-8bcb-cec021f74870.png)

The problem only occurs with some screen widths: no problem with mobile screens or with wide enough screens.

**Comment by fjacon** [comment]
it works fine for me with your URL :
![graphe1](https://user-images.githubusercontent.com/1583203/32336313-3ec1e158-bfef-11e7-92a6-07fd648a5700.png)

**Comment by asaunier** [comment]
Try to reduce the width of your screen and then reload the page.

**Comment by fjacon** [comment]
ok, @julsbreakdown some work for you :-)

**Comment by asaunier** [comment]
A simple/simplist solution would be to display those ``multiselect-box`` always in a single column. For instance by removing those lines: https://github.com/c2corg/v6_ui/blob/master/less/filters.less#L250-L252
I get:
![capture du 2017-11-02 17-06-55](https://user-images.githubusercontent.com/1192331/32336694-40122864-bff0-11e7-8d5f-59ce05e0a08c.png)

It's OK if there is not much options. For longer lists (eg. waypoint types) it's a bit a pity:
![capture du 2017-11-02 17-07-54](https://user-images.githubusercontent.com/1192331/32336753-6fe8504a-bff0-11e7-9718-9a9ef64e9c15.png)

I guess we have to deal with the ``@media`` settings:
https://github.com/c2corg/v6_ui/blob/master/less/filters.less#L249-L276
to finetune when 2 columns are used instead of one.

@julsbreakdown have fun :)

**Comment by desnoes** [comment]
Test on Samsung Galaxy J5 with Chrome => ok
Test on a PC with Chrome (very large screen) => ok
