### ISSUE TITLE
'altitude du début des difficultés' and 'dénivelé des difficultés' criteria are not taken account in results

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1277]
Selected acitivty : climbing, Rocher Haute Montagne (RHM), Neige Glace et Mixte (NGM)
The advanced search does not take into account these fields in the proposed results.

**Comment by desnoes** [comment]
I created a separated issue to avoid too big ones like #655

**Comment by stef74** [comment]
Please add label bug for this kind of issue

**Comment by tsauerwein** [comment]
What document type are you searching for?

For example the following search only returns outings with either `rock_climbing`, `mountain_climbing` or `snow_ice_mixed` (OR not not AND!):
https://www.camptocamp.org/outings#bbox=-1170323%252C3459763%252C1970322%252C7740236&act=rock_climbing%252Cmountain_climbing%252Csnow_ice_mixed

**Comment by fbunoz** [comment]
> What document type are you searching for?

We search any routes with a critera on difficulty elevation or difficulties height diff.
The criteria appears on the filter when selecting a climbing activity (snow, ice, rock, moutain climbing). But the criteria is not taken account in the DB request.
For example : 8030 results with rock climbing and 2 criteria on difficulties : https://www.camptocamp.org/routes#act=rock_climbing&dhei=400%252C3000&ralt=1200%252C6000
But without difficulties criteria, there are the same number of results : https://www.camptocamp.org/routes#act=rock_climbing
(unckeck the map check box to have 8030 results)

**Comment by Kryst0f** [comment]
>>>>What document type are you searching for?

Right now, routes criteria are not available on outings search. 
Therefore, the issue concerns only routes for _rock_climbing_, _mountain_climbing_ and _snow_ice_mixed_.
It works fine for ice_climbing routes.

As soon the routes criteria will be available on outings, we also will need the same search on outings.

**Comment by asaunier** [comment]
@Kryst0f This issue is about route criterias not taken into account in the routes search. Not outing search.

> For example : 8030 results with rock climbing and 2 criteria on difficulties : https://www.camptocamp.org/routes#act=rock_climbing&dhei=400%252C3000&ralt=1200%252C6000 

Here are the filters actually sent to the API by the example search above:
```
act: rock_climbing
dhei: 400,3000
ralt: 1200,6000
bbox: -933062,3511128,1733061,7688871
pl:fr
```

``dhei`` is indeed a range criteria for routes: https://github.com/c2corg/v6_api/blob/master/c2corg_api/search/mappings/route_mapping.py#L41-L42

Ditto for ``ralt`` https://github.com/c2corg/v6_api/blob/master/c2corg_api/search/mappings/route_mapping.py#L37-L38

Both are related to actual route properties:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/route.py#L49
https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/route.py#L55

So nothing wrong at first sight. But indeed those attributes seem to be ignored.

Another broken example with rock_climbing routes with 200 m < ``height_diff_difficulties`` < 300 m near Chamonix: https://www.camptocamp.org/routes#act=rock_climbing&dhei=200%252C300&bbox=750510%252C5736183%252C792168%252C5801461

**Comment by Kryst0f** [comment]
@asaunier Alex, in order to respond to tsauerwein i  already said : 
[quote]
Therefore the issue don't concern outings search.
[/quote]

**Comment by AlexisDemongeot** [comment]
@asaunier @tsauerwein @Kryst0f 

It may concern ice routes too. I searched :"https://www.camptocamp.org/routes#bbox=613364%252C5605091%252C715484%252C5738398&act=ice_climbing&irat=4%252B%252C5&time=1%252C1&hdif=200%252C1500&dhei=200%252C400" 

And it appears some routes in Plancol : 
![image](https://cloud.githubusercontent.com/assets/24522280/22240592/1db403b2-e21c-11e6-9c4d-6f2d4b6199f6.png)

That route with only 40m of difficulties should not appear in the results, isn'it ?

@asaunier wrote : "So nothing wrong at first sight. But indeed those attributes seem to be ignored."

Perhaps, it's and "or" and not "and" in the results ? If it is, the results are correct.

**Comment by desnoes** [comment]
fixed on demo
