### ISSUE TITLE
Modification follow

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1323]
We need a report of all modification in topoguide.

The first implementation can be only with API ( online exist to consert json in excel ... so moderator can easly do this conversion )

Probably more an API issues

**Comment by asaunier** [comment]
@stef74 @desnoes A UI part is being developped, see #1466 
A UI URL will be avalaible: http://.../whatsnew
Should a link be made available somewhere or will the page only be accessible by typing the URL in the browser address bar?

**Comment by fbunoz** [comment]
It would be useful having a link on the profile of an user, and on each doc type filter page (but I don't know where : at the bottom of the list ?).

**Comment by desnoes** [comment]
@asaunier : This will only be used by moderators => typing URL in the address bar is fine for me.

**Comment by brunobesson** [comment]
Sorry, I don't agree. IMHO it's a nonsense not to have a link to it. As far as I understand, there is only one page, not specific ones for different type of documents?
If so, adding the link to the user menu for moderators until we find a better place is OK for me.

**Comment by asaunier** [comment]
I don't understand why this page would be limited to moderators. It's interesting for any users, including guest users, to see what changes are done. It also insists on the fact that c2corg is a collaborative website.
Anyway there is no access restriction applied to this page: anyone that knows the URL can access it.

Adding the link to the user menu does not make sense to me since it is not a user-related feature.

It could be added in the home page near other links such as the "see outings with my filters" button (see https://github.com/c2corg/v6_ui/issues/1342)

Please note that is is possible to filter the list on a given contributor to see their contributions. For instance ``whatsnew?u=12345``.
This link could be added to the profile page (similarly to the "see this user's outings" button at the beginning of the user's feed).

For the first version of the feature, we could say no explicit link is made available. But that's probably worth thinking how to make the tool public.

**Comment by brunobesson** [comment]
>I don't understand why this page would be limited to moderators

You're right. I had thought likewise in the begining, then forgot.

**Comment by desnoes** [comment]
works very fine on demo (see discussions and comment in https://github.com/c2corg/v6_ui/pull/1466)
