### ISSUE TITLE
Add wind rose to route and climbing site edition preview

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_ui#1335]
It's missing...

**Comment by asaunier** [comment]
In the ``climbing_outdoor_site`` waypoints as well.
Actually it seems the windrose is displayed when previewing those WP but the selected orientations are not shown.

For routes, I think there is nothing yet!?

**Comment by brunobesson** [comment]
You're right.Adding the windrose for the route preview is pretty easy, but then there is the same problem as for climbing_sites. I assume there is a problem linking data with the SVG. I won't be able to investigate this soon.

**Comment by brunobesson** [comment]
>In the climbing_outdoor_site waypoints as well.

I updated the issue title accordingly.

**Comment by fbunoz** [comment]
The text (N, E, S, W) is not clickable.
To correct this, add #orientation-svg text to an existing CSS rule : 
```
.filter.orientation #ori-e,
.filter.orientation #ori-n,
.filter.orientation #ori-ne,
.filter.orientation #ori-nw,
.filter.orientation #ori-s,
.filter.orientation #ori-se,
.filter.orientation #ori-sw,
.filter.orientation #ori-w,
.form-group #ori-e,
.form-group #ori-n,
.form-group #ori-ne,
.form-group #ori-nw,
.form-group #ori-s,
.form-group #ori-se,
.form-group #ori-sw,
.form-group #ori-w,
#orientation-svg text
{
    cursor: pointer;
    transition: all 0.3s ease-in-out 0s;
}
```

More over, this rule can be simplified : 
```
#orientation-svg path,
#orientation-svg text
{
    cursor: pointer;
    transition: all 0.3s ease-in-out 0s;
}
```

**Comment by fbunoz** [comment]
The text N, E, S, W would be more readable with a bigger font size : font-size="60".

**Comment by brunobesson** [comment]
@fbunoz please open another issue or make a PR for this. Your comments are welcome but not related to this issue.

**Comment by fbunoz** [comment]
> Your comments are welcome but not related to this issue.

??? Is it not the issue about the rosace design you modified recently ?

**Comment by brunobesson** [comment]
This issue is related to the wind rose in previews. It is absent for routes, and does not show selected orientations when displayed.

**Comment by fbunoz** [comment]
Ok, but I didn't find another the issue related to the resace design. I read a mail about your changes of the design with a comment including a screen shot, but I don't find the issue with this comment.

**Comment by brunobesson** [comment]
>Ok, but I didn't find another issue related to the resace design

You're right, I proposed a PR and discussed it in the forums, but didn't create an issue for this.

**Comment by brunobesson** [comment]
@stef74 I removed the Association label. This is rather a bug that should be handled by SA (which doesn't mean we can't do it by ourselves).

**Comment by fbunoz** [comment]
To precise the bug : the wind rose appears in the preview, only if some directions are selected in the form, but the selected directions are not highlighted on the wind rose.

**Comment by asaunier** [comment]
I suspect the problem comes from this helper functions used both in the view and preview templates:
* routes: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/route/helpers/view.html#L26-L41
* waypoints: https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/helpers/view.html#L400-L415

especially this piece of code:
```
% if waypoint.get('orientations'):
    ${show_orientations('detailsCtrl', 'detailsCtrl.documentService.document')}
% endif
```

It works in the "view" page but in the preview modal, the ``viewDetails`` directive (https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/viewdetails.js) is not used, thus its controller instance ``detailsCtrl`` does not exist and cannot be used in helper ``show_orientations`` defined in https://raw.githubusercontent.com/c2corg/v6_ui/master/c2corg_ui/templates/helpers/orientations.svg

We should:
* either add a special controller to be used in the orientation helper above when previewing
* or directly pass the orientation values to the helper (not through an angular controller). That's probably the easiest even though it might require to duplicate the ``show_orientations`` helper function (perhaps it could be used for the "view" page as well since this page does not require as much interactivity than in the editing form where users can select/unselect orientations).
