### ISSUE TITLE
Pages with many associated images are very long to load

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1409]
For instance this profile with ~350 associated images: https://www.camptocamp.org/profiles/8243/fr

**Comment by dkocich** [comment]
That slider should be really rewritten to not make 350 requests at once (after opening the first picture I was at 80 MB of downloaded data).
Other example for testing - this article has around 530 images (15s loading time on localhost - it do not work on prod. now because of different bug)
https://www.camptocamp.org/articles/465897/fr/concours-photo-sophie-2013 .
