### ISSUE TITLE
Display difficulty of a route on mobile

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1497]
When a route has different styles for difficulty (shashahani, labande...), the display of difficulty in the card of the feed is incorrect.
example:
![card multi actvity mobile](https://cloud.githubusercontent.com/assets/19892089/22917641/4297db84-f286-11e6-8314-3ea29dbf946d.png)
and the desktop version of the same card:
![card multi actvity desktop](https://cloud.githubusercontent.com/assets/19892089/22917653/541b88f6-f286-11e6-8c79-81677ee46c09.jpg)

**Comment by brunobesson** [comment]
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/card.js#L188-L268

On mobile, `getGlobalRatings` is used, while `getFullRatings` is used otherwise.
I don't understand why a distinction is made. Is it assuming the ratings may be too wide on mobile?

I'd rather use only `getFullRatings` function, but there must be a reason for it. @asaunier?

**Comment by stef74** [comment]
Yes is not a bug ... it's correct behavior (wanted by assoication) ... but we can show full rating at all time.

**Comment by brunobesson** [comment]
>wanted by assoication

Could you elaborate? I didn't follow the discussions in the working group, but don't understant the goal?

**Comment by stef74** [comment]
I cannot give more eplanation than is in specification : https://docs.google.com/spreadsheets/d/1W2kEAyGPc7cw9yKe3hyYIMTNgUDLPsFUD0ccTS8jI5Y/edit

**Comment by desnoes** [comment]
I suggest to switch to full rating. There is enough space on the card on mobile.

**Comment by stef74** [comment]
@desnoes for me is fix since few weeks.
