### ISSUE TITLE
Anonymize xreport

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1507]
A user should be able to choose to hide his name when the report is publicly displayed.
A check box should be inserted in the creation form to offer this choice.

**Comment by asaunier** [comment]
Is it OK if this is handled on the UI side only (the template does not show the associated users section if the box is checked)? Or should we make sure the API does not return at all the list of associated users?

Option 1 is much easier. Is it enough?

Anyway please note that making the report anonymous will most likely make it no longer possible to edit.
Because editing credentials are related to associated users. Unless the associated users are still provided to the client code but not displayed (which is a quite superficial anonymization).

Depending on the requirements of this demand, it can become quite difficult to implement.

**Comment by stef74** [comment]
Yes for me UI approach is sufficient. If user want really anonymised contribution ... it use an other account.

**Comment by desnoes** [comment]
@asaunier: for me it's ok, We shall add a clear statement about this constraint when a user creates the report.
@mgerbaux: what is your opinion ?

**Comment by mgerbaux** [comment]
In my point of view, It could be only a short term patch to do this only in UI ; It is not the way to make a confidante relationship with the users.
Maybe the time to make some work on API to pass author as private argument ?

> If user want really anonymised contribution ... it use an other account.
It is not the way to encourage and facilitate contributions asked by our partner

Note that anonymization should also be done in the versions data (maybe an other issue related to all personnal documents).

**Comment by asaunier** [comment]
> Maybe the time to make some work on API to pass author as private argument ?

You mean it would be passed like the personal data?

> Note that anonymization should also be done in the versions data (maybe an other issue related to all personnal documents).

Associations are not integrated in archived versions and are independent (ditto for all document types).

**Comment by asaunier** [comment]
## Approach 1, allowing to make an existing or new report anonymous 

TODO:

API side:
* [ ] add an "anonymous" boolean attribute to the data model https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/xreport.py
* [ ] remove attributes ``author`` and ``users`` from the the "detail" data if ``anonymous`` is true (already OK for the "list" request: no user info is provided in these data)
* [ ] disable the history request (for all xreports)? => problem: there is only one service for all document types https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/document_history.py
* [ ] disable the old versions service: https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/xreport.py#L103
* [ ] preventing from associating users => no one is associated to the report, only the initial (and only) author is displayed if not anonymous
* [ ] alembic script to remove the users association

UI side:
* [ ] remove history/archive routes and views for xreports + the entry in the "plus" button menu
* [ ] update xreport view page to remove the author/users section if anonymous is checked
* [ ] for all reports: remove the "participants" section  which is useless (this is not an outing!)
* [ ] update xreport editing form to add the "anonymous" checkbox and the participants association tool

Please note making a report anonymous will remove the user info from the API response => it will no longer possible to edit the report except for moderators!

**Comment by asaunier** [comment]
## Approach 2: only allow users to make a new report anonymous (existing reports can not be made anonymous)

The existing behaviour remains unchanged except that:
* the editing form provides an ``anonymous`` checkbox when creating the report (not available when editing the report)
* if checked, the API uses a special user account ("Camptocamp Association"?) as the author, instead of the actual user account of the creator. The special user account appears in the history of the report.
* the document can no longer be edited, except by moderators or by the special user account.

Question: should we also disable participants associations (see approach 1)?

TODO:

API side:
* [ ] add an "anonymous" boolean attribute to the data model https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/xreport.py
* [ ] replace the reference to the creator user account by a reference to a special user account (TBD)

UI side:
* [ ] update xreport editing form to add the "anonymous" checkbox

**Comment by desnoes** [comment]
@mgerbaux: I don't remember the exact requirement. Does anonymization means complete anonymization (author's name is lost) or only the author's name shall be accessible to researchers and only them ?
My understanding of anonymization is complete anonymization. This would avoid misleading interpretations. In this case, i think approach 2 is sufficient. 
What is your opinion ?

**Comment by mgerbaux** [comment]
> @mgerbaux: I don't remember the exact requirement. 

To be able to create a xreports without the user's name appears publicly. If it is simpler, this name can be seen by moderators or researchers.
Ideally, a user that have created an anonymous report should be able to edit it.

To my mind, Option 2 is better, despite it should not allow to edit xreports, or simply to add images to the report. I do not understand the interest of disabling participant association.

**Comment by asaunier** [comment]
> If it is simpler, this name can be seen by moderators or researchers.

Researchers have no existence in our permission system: if they have a user account they have the same permissions than standard users.

> a user that have created an anonymous report should be able to edit it.

As I said it this is probably not possible because:
* the UI server knows nothing about users => all generated pages are the same for every one (anonymous, authenticated users, moderators).
* the UI client (javascript code run in the users browsers) gets authentication info directly from the API and decides if the editing tools are provided (the API also checks the permission when receiving editing requests).
* if creator data are not provided by the API for anonymous reports (as you requested at https://github.com/c2corg/v6_ui/issues/1507#issuecomment-281291084), the UI client has no way to figure out if the current user has write permissions, thus will not provided editing tools.

> simply to add images to the report

Indeed. Creating an anonymous report will probably prevent from adding images to the report because you need to have write permissions to be able to upload an image. In addition if it was possible, we would need to make the image anonymous as well...

Honestly I have the feeling that allowing anonymous reports will bring quite a log of complexity without being that useful: most contributors are already using pseudonyms (~anonymous) instead of they real names, in addition it is easily possible to create an dummy account.

**Comment by asaunier** [comment]
> I do not understand the interest of disabling participant association.

* Because associating participants to an xreport is quite inconsistent. Xreports have a personal data section with attributes related to the reporter. But who is the reporter if several users may edit the report?
* Because an xreport is not an outing.
* Because if approach 1 described above is implemented (and history removed), we would no longer be able to figure who are the authors of the report, which is contradictory with the CC licence, except if there is only one author, explicitely mentioned in the document.

**Comment by mgerbaux** [comment]
>Researchers have no existence in our permission system: if they have a user account they have the same permissions than standard users.

I meant that anonymization was not a problem for dump extraction of SERAC database

>Honestly I have the feeling that allowing anonymous reports will bring quite a log of complexity without being that useful

I agree, but this point is not questionable in our partnership

> Creating an anonymous report will probably prevent from adding images

You are right!
I suggest to take your approach 2, and add a textual message close to the "anonymous" checkbox to explain all the disagreements checking this case will done.

**Comment by desnoes** [comment]
> I suggest to take your approach 2, and add a textual message close to the "anonymous" checkbox to explain all the disagreements checking this case will done.

I agree with this position. Anonymization implies some contraints and users that select this option have to leave with it.

**Comment by asaunier** [comment]
Approach 2 has been implemented, see the explanations and screenshots at https://github.com/c2corg/v6_ui/pull/1720#issuecomment-313068446 and https://github.com/c2corg/v6_api/pull/674#issuecomment-313062994

**Comment by desnoes** [comment]
nice job!
