### ISSUE TITLE
Block comments on xreports and outings

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1515]
An user should be able to authorize or ban comments from other users on its personnal reports:

- xreport: mandatory
- outing: likely

**Comment by asaunier** [comment]
@desnoes Could you precise the need:
* could you confirm what is asked is only to allow/disallow comments in an outing/xreport, not to give moderation rights on comments to the outing's associated users?
* would the ban be on a per-document basis, using for instance a checkbox in the editing form?
* would it be possible to change the policy by editing the document and (un)checking the checkbox? What would happen if a user disallow comments after comments have already been posted? Would comments be deleted? hidden? Would it be no longer possible to disallow comments when there are existing comments?

> xreport: mandatory

Does this mean that comments would anyway be disabled for xreports? (the author would then not even have the choice to allow comments)

**Comment by desnoes** [comment]
> could you confirm what is asked is only to allow/disallow comments in an outing/xreport, not to give moderation rights on comments to the outing's associated users?

Could you explain? I am not sure i understood the difference between the 2 options.

> would the ban be on a per-document basis, using for instance a checkbox in the editing form?

From my personal point of view, the answer is yes.

> would it be possible to change the policy by editing the document and (un)checking the checkbox? What would happen if a user disallow comments after comments have already been posted? Would comments be deleted? hidden? Would it be no longer possible to disallow comments when there are existing comments?

I would select the simpliest option: no modification of policy by editing the document. If a problem arises it is still possible to delete comments manually.

> Does this mean that comments would anyway be disabled for xreports? (the author would then not even have the choice to allow comments)

No, i meant the requirement (possibility to allow/disallow comment) is mandatory for xreport, while it is "a nice to have" functionnality for outing. If it is simpler to implement the same procedure for xreport and outing, this is great. If additional complexity is implied for outing, then the requirement can be dropped for outings.

@mgerbaux : what is your opinion ?

**Comment by asaunier** [comment]
> I am not sure i understood the difference between the 2 options.

* option 1: the user decide whether or not comments are allowed in the outing
* option 2: the user can remove (edit?) some of the comments posted in the outing => kind of moderation rights as sometimes suggested in the association forum. But I think it is really complicated and would not recommend this option.

>  i meant the requirement (possibility to allow/disallow comment) is mandatory for xreport, while it is "a nice to have" functionnality for outing.

Xreports and outings are 2 distinct types of documents. Implementing this feature for both types would be similar: we would do it for one type and apply the changes to the other type as well.

**Comment by mgerbaux** [comment]
> option 1: the user decides whether or not comments are allowed in the outing

That is what should be done for me (for xreports and outings).

This choice should be offer when creating / editing the document

**Comment by asaunier** [comment]
> This choice should be offer when creating / editing the document

What happens if the user disable comments while there are existing documents?

A quite simple behaviour could be:
* we add a "disable comments" attribute to outings and xreports, that could be checked/unchecked in the editing form
* if "disable comments" is true (checked), the comments section is hidden whether there are existing comments or not => not "add comment" button, no list of existing comments. But the topic containing the existing comments remains unchanged in Discourse.
* if the document is edited and "disable comments" is later unchecked, the "add comment" button is shown back, as well as existing comments if any.

Sounds good?

TODO:
* [ ] add ``disable comments`` attribute to the API for outings and xreports models + to the list of attributes in https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_outing.py#L2 (ditto for xreports)
* [ ] add ``disable comments`` to the editing forms
* [ ] show/hide the comments section (ditto for the "comments" button in the right-floating buttons) depending in the value of  ``disable comments`` https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/outing/view.html#L162

**Comment by desnoes** [comment]
>option 1: the user decide whether or not comments are allowed in the outing

I share Martin's position. It's the best choice.

> Sounds good?

yes, it's good to me. If required for some cases, former comments can be deleted manually.

**Comment by mgerbaux** [comment]
> Sounds good?

Go !

**Comment by mgerbaux** [comment]
It sounds good for me.
Nice job !
