### ISSUE TITLE
Image infos

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1535]
When you use this syntaxte : [img=857571] test [/img] the information show are not correct ... 

![image](https://cloud.githubusercontent.com/assets/3962997/23547893/446f2d86-0005-11e7-8075-48b8dd40ad53.PNG)

**Comment by stef74** [comment]
A probably link issue ... that sometime we can show exif infos (correctly display) with this step to reproduce : 
    Cliquer sur une image dans les commentaires
    Cliquer sur le bouton infos ⓘ
    Fermer l'apperçu Ｘ

Chaque image dans les commentaires à alors toutes les infos exif affichées de la photo précédemment sélectionnée.

**Comment by stef74** [comment]
An other thing if I can see image toolbar 

![capture](https://cloud.githubusercontent.com/assets/3962997/23551618/e6300264-0017-11e7-9174-4c67ce88b16e.PNG)

**Comment by asaunier** [comment]
Can be tested in this outing: https://www.camptocamp.org/outings/857542/fr/breitwangflue-flying-circus

> When you use this syntaxte : [img=857571] test [/img] the information show are not correct ...

It seems the "infos" title that is automatically added is the "infos" section that is displayed in the slideshow when clicking the "i" button.

When the page is first loaded, an "infos" title is shown below the image:

<img width="476" alt="capture d ecran 2017-03-03 a 14 47 52" src="https://cloud.githubusercontent.com/assets/1192331/23553309/87c0a644-0020-11e7-915a-b07fb1c6a434.png">

If I click on the image, the slideshow is shown. If I click on the "i" button, metadata are shown in the slideshow. After closing the slideshow, those metadata are shown in the text of the outing:

<img width="452" alt="capture d ecran 2017-03-03 a 14 45 39" src="https://cloud.githubusercontent.com/assets/1192331/23553393/dd04f164-0020-11e7-8542-9446d01d5600.png">

> An other thing if I can see image toolbar

Indeed.

In addition there is no border around the embedded images.

On the other hand all those weird behaviours cannot be observed in a route document. For instance https://www.camptocamp.org/routes/857378/fr/breitwangflue-flying-circus

<img width="388" alt="capture d ecran 2017-03-03 a 14 54 55" src="https://cloud.githubusercontent.com/assets/1192331/23553520/67849a4c-0021-11e7-9bb8-27d8d6458fcf.png">

=> borders and legend are shown as expected 
=> no "infos" title is shown under the image
=> no metadata is shown under the image (OK in the slideshow).

It seems something is incorrect in the outings, creating a conflict with the slideshow!?

**Comment by brunobesson** [comment]
I remember we already encoutnered something similar. Don't have time to loog for it now, but it was because of the CSS applied. To function normally it expected something like `.document-description`, which was present only in the main field and not the others.

**Comment by asaunier** [comment]
@brunobesson Thanks for the tip!

I notice that outing's description attribute uses the standard ``get_document_locale_text`` helper instead of ``get_document_description`` as for the routes:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/outing/view.html#L138
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/route/view.html#L131

I have tried to use the latter helper in outings as well and it seems to work. See https://github.com/c2corg/v6_ui/pull/1536

I think you have introduced this ``get_document_description`` helper. Do you remember why you had not used it for the outings?
Could you check that the change above is correct?
Thanks!

**Comment by brunobesson** [comment]
This will work for this field, because it will add the `view-details-description` class to the outer section. However, this won't work in the other ones. Maybe I could have a longer look this evening, modifying the CSS could be a better option.

>I think you have introduced this

I think (but am not sure), I only extended it to allow for the title option, because it was need for some fields whose title depends on context.

**Comment by stef74** [comment]
For me is not correct on demo 
![capture d ecran 2017-03-19 a 20 20 17](https://cloud.githubusercontent.com/assets/3962997/24083962/89d1ab9a-0ce1-11e7-8631-141cc186349d.png)
http://www.demov6.camptocamp.org/outings/826903/fr/pointe-de-chavasse-face-se-depuis-le-col-de-la-ramaz

**Comment by asaunier** [comment]
The changes done in the related PR https://github.com/c2corg/v6_ui/pull/1536/files only concern the "personal comments" attribute, not the weather or conditions attributes.

**Comment by desnoes** [comment]
The bug is fixed on demo
