### ISSUE TITLE
Advanced search display on mobile

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1622]
The filter area is floating and moves to the left when i try to move the right par of a slider.
Chrome (last version)
![screenshot_20170504-190753](https://cloud.githubusercontent.com/assets/19892089/25736897/0937d58c-3175-11e7-9bdc-a2ca55b4329e.png)

**Comment by asaunier** [comment]
I indeed observe this behaviour on my android phone with Chrome (not tested with another problem).
At least the page remains correctly usable: it is still possible to scroll down and this behaviour occurs only when the filters section is open while panning to the right.

I suspect this is caused by the buttons "More filters" / "Clear filters" / "Load my preferences" that are shown on the same line whereas there is not enough width to show them all:
![capture du 2017-05-18 14-37-05](https://cloud.githubusercontent.com/assets/1192331/26202404/a0923fdc-3bd7-11e7-83bd-58f2dc3d3145.png)

When clicking on "More filters", the buttons are dispatched on several lines, eg.
![capture du 2017-05-18 14-39-28](https://cloud.githubusercontent.com/assets/1192331/26202453/d1abb5bc-3bd7-11e7-88b5-522b8b622f99.png)
