### ISSUE TITLE
Better handling of default "c2c" account in Transifex

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#1747]
A default "c2c" account is used by Travis (and developers?) to retrieve ("pull") translations for Transifex.
A few days ago it seems that something changed in Transifex, preventing Travis from pulling the translations and building the docker images.

To make it work I had to add the default "c2c" user to the translation teams in Transifex despite this account is poorly protected (password is more or less public). A more secure solution is probably required.

**Comment by tsauerwein** [comment]
The credentials do not have to be public. For Travis, the best would be to set them as *secret* environment variables (https://travis-ci.org/c2corg/v6_ui/settings) and then use the variables to create the config file.

And instead of using user/password, a token can be generated, see: https://docs.transifex.com/api/introduction

This token should also be set as environment variable for Travis.
