### ISSUE TITLE
Search of hiking/VTT routes does not work with exposure rating

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#1750]
Most of hikking routes do not have a value for the exposure rating. In the advanced search, when filtering on e.g. E1-E3, all routes are removed from the result. In this example it should be better to also display all routes that do not have exposure rating.
![recherche rando exposotion 1-4](https://user-images.githubusercontent.com/19892089/28202460-c09944e0-6875-11e7-811e-5d9434c8072c.png)
![recherche rando exposotion 1-3](https://user-images.githubusercontent.com/19892089/28202469-ca33249e-6875-11e7-9810-854ee6c418dc.png)

**Comment by asaunier** [comment]
This "problem" is more general: for instance if you filter on toponeige ski ratings > 3.1, all ski routes with no toponeige ski rating provided will be ignored.

I wrote "problem" with quotes because is it really a problem? I mean that it is consistent when using a given filter to return only results matching the filter. If the attribute is not set for a document, the latter does not match the result.

**Comment by desnoes** [comment]
This is not a bug, the filter does its job. But this is still a problem for an user.
