### ISSUE TITLE
Improve area post it

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#1884]
In outings and routes, the yellow areas post-it sometimes overlap with content below it

**Comment by brunobesson** [comment]
Honestly, I think you could be more explicit in the title and description. I did understand only because I have been working on the website for a few hours :rofl: 

Something like `In outings and routes, the yellow areas post-it sometimes overlap with content below it` + screenshot would be more obvious, don't you think?

**Comment by asaunier** [comment]
What about getting rid of the post-its and move their content to some more standard places?

**Comment by brunobesson** [comment]
>What about getting rid of the post-its and move their content to some more standard places?

I second you on that proposal.

**Comment by stef74** [comment]
Agree to delete the post-it and add the content on doc directly. The question si where ... dedicated place or with the general information
 ?
