### ISSUE TITLE
Non breakable spaces should be inserted after arabic numbers

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_ui#1970]
Typography : an arabic number should never be separated from the word that follow. For instance, in '123 cows', cows must not be in a new line.

**Comment by fbunoz** [comment]
An improvement would be to use a narrow nbsp when the word after the number contains 1 to 3 letters. A word = alphabetic characters.
3 m => narrow
3 km => narrow
3 km/h => narrow (word = km (2 letters))
3 MWh => narrow
3 spit => normal
3 pitons => normal
3 p => narrow

Another improvement would be to add a narrow nbsp between arabic number and alphabetic letters if a word start with an arabic number.
30m => 30 m
3p => 3 p
3pitons => 3 pitons (with narrow nbsp. It's just a (good) side effect when a space is missing).

**Comment by cbeauchesne** [comment]
Fo the first case, if I've understand well, is between an unit (m, km/h, p for pitons) and a enumerable item (cow, spit, bananas, ...)? If yes, another solution would be to list all acceptable units if it's possible. By the I've never seen that typographic convention recommand to use narrow space for units, do you have some document on this? (humbly, I've followed what WP says about that, I do not pretend to be an expert).

For the second case, I disagree : the parser must improve what redactor wrote, but only to a certain point: 

* We have no doubt if a writer wrote "123 cows" that 123 applies to cows, and thus should not be separated. 
* But saying that "3pitons" is a typo that should be "saved' by the parser is IMO an error.

For instance, how could we be sure that if a writer wrote "6A" that he wants to means the climbing grade 6A, or 6 Amperes?

This use case of misssplelling is preferably handled by a bot that flags such typo, letting a human to decide to correct it, or not, and keeping the parser very rigourous.

**Comment by fbunoz** [comment]
> Fo the first case, if I've understand well, is between an unit (m, km/h, p for pitons) and a enumerable item (cow, spit, bananas, ...)?

narrow space between number and unit, but normal space between number and enumerable item.
A unit list could a solution to avoid side effect (evven if it's not catastrophic if sometime there is a narrow space betwween a number and  an enumerable item with a 3 letters word).

>  I've never seen that typographic convention recommand to use narrow space for units, do you have some document on this?

It's just a new typo rule since 23-01-2018 21:15 :-)

I discover today the existence of narrow nbsp.
As explained in the [typographic rules](https://www.camptocamp.org/articles/106920/fr/aide-topoguide-presentation#regles-typographiques), in topoguide text, we use the notation : 2300m, 35m, 1h, 45min, without any space between numer and unit, to avoid a line break at this point.
A disadvantage is a smaller readability (on a mobile in the rain, on a old paper print, etc), as numbers are less visible (ex : 1km/h - 1 km/h ).
But if we could automatically use nbsp, we can allow a space.
But adding a space in "35m" (=> "35 m") extends the width of the length column in a ltag table.
A good compromise is to use a narrow nbsp.

> For instance, how could we be sure that if a writer wrote "6A" that he wants to means the climbing grade 6A, or 6 Amperes?

Sorry, I forgot this case (as "6a+" => "6 a+").
[On V5](https://www.camptocamp.org/articles/version/151910/fr/1263913), there were these rules : 

> Par ailleurs, un simple espace est automatiquement remplacé par un espace insécable dans les cas suivant (inutile donc d'utiliser l'astuce ci-dessus) :
> - espace devant ? ou ! ou :
> - espace séparant des chiffres
> - espace séparant un chiffre et un mot
> Dans ce dernier cas, si le mot est m, cm, dm, hm, km, mn, min, h, hr ou s, l'espace est supprimé (sauf dans certains cas, c'est buggué, pas grave).

A space between a number and an unit was removed. Because I didn't know narrow nbsp.

For years we educate the contributors to not add space between number and units. Then we should tell them to do the opposite since today...

**Comment by cbeauchesne** [comment]
For the first point, no technical matter. But functionnaly, I think it's better to follow conventions used verywhere, instead of reinventing new one : the reading comfort is often a question of habits. BTW, it must be discuss on the forum.

For the second point, it's the kind of hack that leads to huge mess in a parser, we can't handle all the side effects. The old recommendation was motivated by a limitation. If we can't tell contributor that this ortogrpahuc fault is now useless, it's preferable to continue with the old style than risks this kind of mess.

But I think that it won't be a big issue, let ask on the forum.

**Comment by desnoes** [comment]
ok on demo (cf. https://www.demov6.camptocamp.org/articles/951530/fr/essai-images)

**Comment by cbeauchesne** [comment]
Ty for testing :)
