### ISSUE TITLE
The first paragraph following a TOC tag doesn't appear 

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#2045]
The parser eats all the text following the [toc] tag, until the first blanking line.
But if the text is a subtitle, it works correctly even without blank line.
Moreover, The [toc] doesn't work if there is a text before the tag without blank line.
Then, the correct syntax is : 
```
Text
_blank line_
[toc]
_blank line_
Text
```

It's acceptable that the [toc] needs blank lines. But a bad syntax shouldn't eat the text, just show the tag without decoding.

Example : 

- Missing text following the tag : https://www.demov6.camptocamp.org/articles/951514/fr/test-niveaux-de-titres
- Non decoded tag : https://www.demov6.camptocamp.org/articles/947724/fr/les-voies-au-dela-du-9b
- Correct syntax : https://www.demov6.camptocamp.org/articles/951517/fr/test-id-de-titre

**Comment by desnoes** [comment]
@cbeauchesne : there is still a bug with the following configuration:
Text
_blank line_

This is clearly not a blocking point.

**Comment by cbeauchesne** [comment]
Well, it's not considered as a bug, as the [toc] tag must surrounded by blank lines.

The point of this issue is that, in case of malformatting, the markdown must be rendered as normal text.

That said, we could consider that your markdown is a valid toc syntax. IMO, for the markdown clarity, I think it's better to keep mandatory blank lines. But I'm open to discussion.

**Comment by desnoes** [comment]
@cbeauchesne : ok, thanks for the explanation. I closed the issue.
