### ISSUE TITLE
multiple checkbox values angular

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_ui#216]
It would be a great idea to retrieve an array of values from a set of checkboxes for one model. For example for climbing-styles we would like to get waypoint.climbing-styles = ['style1', 'style2'] etc. Do we have something in place to handle that? 

If no, I suggest using http://vitalets.github.io/checklist-model/, I have used it once and it does its job pretty well. Creating something like this from scratch seems a little bit complex and implies some new data/html/js structure levels.

**Comment by asaunier** [comment]
I definitely think that we should rather use checkboxes instead of  multiselect lists because users often don't know it is possible to use the Ctrl key to add/remove options to the selection => checkboxes are more intuitive.

We already have an issue for this: https://github.com/c2corg/v6_ui/issues/49

The directive you mention seems interesting. I would be +1 to use it (does it add much filesize to download the lib?).

**Comment by asaunier** [comment]
@ginold Can we close this issue?

**Comment by ginold** [comment]
yes, we can! i finally managed to do it myself.
