### ISSUE TITLE
Use default geometry for outings and routes in listing views

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#230]
With https://github.com/c2corg/v6_api/pull/179 outings and routes now have a `geom_detail` field which contains the full track. The field `geom` contains a point geometry which can be used in listing pages.

**Comment by asaunier** [comment]
To summarize:
* for list pages: use the point geometry (``geom``) to place/filter outings and routes on the map
* for route detail pages:
 * use the detailed geometry if available to show it on the map. If not available, show no geom.
 * show the associated WP geoms anyway.
* for outing page
 * use the detailed geometry if available to show it on the map.
 * not sure if we should show the associated routes detailed geometries if available (that might be a bit confusing because visitors might not figure out the tracks are not the actual outing track). Or only on demand, for instance when hovering the associated route cards?
 * if no detailed geom is available, perhaps we could simply recenter the map on the point ``geom`` (default geometry). Or show no map at all as in v5 (but I think showing a map anyway is interesting to figure out where the outing took place).
* detail pages of WP:
 * show the ``geom`` of the the WP (always available) => map is centered on it
 * show the associated WP geom?
 * show the associated routes detailed geom if available? no need to show the point default geom if no detailed geom is available.

**Comment by tsauerwein** [comment]
> for route detail pages:
> 
>  * use the detailed geometry if available to show it on the map. If not available, show no geom.

For routes and outings, if no detail geometry is available, we could show the point geometry, so that you have at least an idea where it is.

Note that currently the geometries for associated documents are not included.

**Comment by asaunier** [comment]
> For routes and outings, if no detail geometry is available, we could show the point geometry, so that you have at least an idea where it is.

For outings it could make sense.
For routes, I think showing the associated WPs is more relevant (even though not available yet :P).
