### ISSUE TITLE
Text formatting shortcuts buttons

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_ui#305]
@asaunier  said Having a graphical editor seems to me too difficult because the syntax used for the documents is too complicated and too customized. I think we should restrict to some shortcut buttons, as in v5 or github etc.

**Comment by fjacon** [comment]
agreed.

**Comment by asaunier** [comment]
I have set this issue to milestone 6.1 because without those shortcuts people will have a hard time writting the correct markdown (and bbcode?) syntax.

By the way for such tools it would make sense to rely on an existing JS library.
After a quick search I have found:
* https://www.npmjs.com/package/angular-markdown-editor / https://github.com/ghiscoding/angular-markdown-editor / demo : http://plnkr.co/AFxN7uiwkZlJ9OMZwXey
* https://github.com/GrumpyWizards/wizMarkdown

Other JS libraries:
* https://simplemde.com/ / https://github.com/NextStepWebs/simplemde-markdown-editor (looks nice!)
* https://github.com/lepture/editor

It would be interesting to know if it is possible to extend such libraries and add our own tags (wikilinks, img, L#, etc.).

I also think we need to get rid of BBcode, I don't think we will find a JS editor that supports both markdown and bbcode... See https://github.com/c2corg/v6_ui/issues/131

**Comment by dkocich** [comment]
note - this editor looks fine too http://textangular.com/ https://github.com/fraywing/textAngular

**Comment by arnaud-morvan** [comment]
It seems that angular-markdown-editor ( https://www.npmjs.com/package/angular-markdown-editor ) already do the job for basic markdown.
We should create our own directive to customise the editor (remove/add buttons).
So we have to create externs for bootstrap-markdown.

Here is a snapshot : 
![markdown-editor](https://cloud.githubusercontent.com/assets/6095494/23996829/35c8fa56-0a4f-11e7-974d-11824e4d9746.png)

There is some css to apply (buttons text color).
If we want to keep the preview, we should apply the same styles as in the document view mode, or we should hide the button for a first time.
We should also hide the image button for the moment.

**Comment by asaunier** [comment]
> If we want to keep the preview, we should apply the same styles as in the document view mode, or we should hide the button for a first time.

Isn't this button a bit redundant with the general preview button in the right sidebar?

**Comment by arnaud-morvan** [comment]
Yes !! if we can remove the markdown editor preview button, we by-pass complex stuff about css.

**Comment by fjacon** [comment]
for me it is OK to go on and have it on demo asap

**Comment by desnoes** [comment]
I made some test in this document: http://www.demov6.camptocamp.org/outings/828446/en/tete-de-vauclave-toto-fait-du-ski 

The insertion of a link does not work. There is a problem when using ordered and unordered lists successively, only the first type of list is selected. If there is another balise in between, it works fine.

There are some translation issues (unordered liste, ordered list, Quote, Help). I guess they are managed by transifex but I did not find the corresponding key words. Could you give the list of key words ?
