### ISSUE TITLE
Elevation/timestamp are removed from GPX tracks

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_ui#331]
* [ ] Make sure elevations/dates are not removed from GPX tracks uploaded in the routes/outings editing forms.

**Comment by asaunier** [comment]
I am not sure it is a UI issue. See https://github.com/c2corg/v6_api/issues/262

**Comment by asaunier** [comment]
I have removed the "alpha 3" milestone from this issue because the issue cannot be fixed on the UI side until elevation/timestamp are supported on the API side (it's not as far as I know).

**Comment by asaunier** [comment]
The milestone of this issue cannot be v6.1 because it impacts the data.

If c2corg/v6_api#262 is not fixed at golive, all migrated geometries will be migrated as 2D and the elevations and times will be lost.
Ditto the elevations of uploaded GPX track in v6 will be lost.

Please note that anyway, drawing a route on the map will only be 2D, unless we set an elevation service to add the elevation to the new points.

**Comment by tsauerwein** [comment]
The API now supports 3D/4D geometries. But the UI does only send geometries with 2 dimensions. The other dimensions are removed.
