### ISSUE TITLE
User profile

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_ui#335]
See https://github.com/c2corg/v6_ui/pull/728 for the TODO

**Comment by asaunier** [comment]
See the "personal documents policy" email discussions (starting March 3rd), there are info about the user profiles. For instance, since one should not be able to view the user profile versions history and old versions => the simplest solution is to not archive the old versions! In addition in v5, contributors may choose to make their user profile not public...
=> this is a very special kind of document
