### ISSUE TITLE
Prevent zoom on map

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#413]
On topoguide,  document have map on top ... this map are zoomed too often until instead go down on the document. It' little bit annoying
How to prevent it ? with click on map before zooming ? no full large screen map ? other ?

**Comment by ginold** [comment]
We have implemented "smart scrolling" because of this problem : when you scroll from the top to the bottom and your mouse cursor will go through the map, it would unintentionally zoom in, which was annoying. But not it will not zoom until it stays for 0.5 sec on the map. So just make sure your pointer is not on the map while scrolling, if not it is actually supposed to zoom in.

**Comment by stef74** [comment]
I think 0.5s is too small. Could you try with 2s.

**Comment by ginold** [comment]
I changed to 1s, 2 seconds is super long.
