### ISSUE TITLE
No contour lines on maps

### ISSUE THREAD

**Issue by LaurentBonnaud** [c2corg/v6_ui#438]
C2Cv6 uses OSM maps that are fine, but lack contour lines (courbes de niveau), which is problem for a mountaineering site.

Would it be possible to use those maps instead (they are based on OSM data, but include contour lines) ?

[http://www.4umaps.eu/online-outdoor-hike-bicycle-map.aspx](http://www.4umaps.eu/online-outdoor-hike-bicycle-map.aspx)

**Comment by asaunier** [comment]
The 4umaps baselayer looks interesting indeed. Thanks for suggesting @LaurentBonnaud !
Actually we currently use OSM as the default baselayer for developing but it will most likely change. See https://github.com/c2corg/v6_ui/issues/67

Using 4umaps baselayer tiles is technically not a problem (similar to OSM). It depends on their terms of use and their pricing (if it's a commercial service).

**Comment by LaurentBonnaud** [comment]
It looks OK:

[http://www.4umaps.eu/terms-of-use-copyright.aspx](http://www.4umaps.eu/terms-of-use-copyright.aspx)

**Comment by asaunier** [comment]
> It looks OK:
http://www.4umaps.eu/terms-of-use-copyright.aspx

OK thanks. Please note they say
> If you expect heavy traffic from your application or website, please contact the web master in advance.

which is probably the case.

Since the map backgrounds are already discussed in https://github.com/c2corg/v6_ui/issues/67 and since I have reported your suggestion in it, I prefer closing the current issue to avoid duplicates.
