### ISSUE TITLE
Defaut map zoom

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_ui#498]
For some route (climbing route ?)  ... the defaut zoom is to higher.

Ex : http://c2corgv6.demo-camptocamp.com/routes/736686/fr ... show only "green", we have to click more than 5 times to have other element like road on the map.

**Comment by asaunier** [comment]
The problem seems to only occur for routes with no own geometry (GPS track => a default point geometry is used instead) since changes have been  made to (partially) add associated WP:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/route/view.html#L60-L75
=> associated WP geometries are missing and that probably causes the incorrect recentering/zooming (if the route has a GPS track, the problem is masked).
=> related to issue https://github.com/c2corg/v6_ui/issues/362

**Comment by ginold** [comment]
In general I find that we should limit the zoom because the tiles are too pixelated and the half of the layers don't even appear at great zoom.

**Comment by asaunier** [comment]
> In general I find that we should limit the zoom because the tiles are too pixelated and the half of the layers don't even appear at great zoom.

We use the default OSM etc. settings with the zoom levels defined for those layers. I don't think we should add extra restrictions, no one forces users to zoom to those zoomlevels :P

**Comment by stef74** [comment]
Is fixed ? for me is not fixed for the moment (demo not updated ?)
![capture](https://cloud.githubusercontent.com/assets/3962997/17055739/0d029d20-500f-11e6-918e-11e8f03f568a.PNG)

**Comment by asaunier** [comment]
> demo not updated ?

Indeed! I have just updated it.

**Comment by stef74** [comment]
Great It's work !
