### ISSUE TITLE
Outing creation: default values for fields

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#499]
(extract of issue #403 that have been closed):
- [ ] In the first step, the fields should be pre-filled either from the associated route or from the GPS track (when associated)
- [x] Step 2: the "Glacier" field should not appear if the associate route(s) have no "matériel glacier". See https://github.com/c2corg/v6_ui/issues/1356

It is the same as in v5 (except pre-fill from GPS track) and it was specified in google sheet "Outing".

**Comment by asaunier** [comment]
@loicperrin Don't forget the * in front of the [ ] when creating a checkbox list (or click on the corresponding button in the toolbar): ``* [ ] ...`` else the checkboxes are not created as expected (I have made the change in this issue and an other).

**Comment by asaunier** [comment]
I also paste my comment from the previous issue: https://github.com/c2corg/v6_ui/issues/403#issuecomment-233600987

> In the first step, the fields should be pre-filled either from the associated route or from the GPS track (when associated)

Setting default values of the outing attributes with the attributes of the associated routes is not a minor task. By the way I don't think this task is listed in the specs. @fjacon what do you think?

**Comment by fjacon** [comment]
For me it is extra work.

**Comment by stef74** [comment]
@fjacon please quote

**Comment by asaunier** [comment]
Auto-filling some outing attributes is not trivial. We also need more precision, for instance on the attributes that should have a default value.

My first question is: is it really relevant to have default values?
I have often noticed that outing attributes are poorly filled because of those default values. For instance incorrect height diff defaulting to the route height diff whereas people have combined several routes or followed only a part of the associated route.
I have the feeling it would be better to leave people fill the fields by themselves.

Second question: if auto-filling is really needed, what outing attributes should be auto-filled and what route attribute should be used to retrieve the default value?

Third question: what should we do when several routes are associated? Consider only the first one?

Depending on what route attributes must be used for auto-filling, we might have to do an extra API request to get the additional route attributes, which would be a pity (more complexity + a lot more data to load). To avoid extra requests, we should restrict to route attributes available in the cards. See https://github.com/c2corg/v6_ui/issues/398

**Comment by stef74** [comment]
@loicperrin could you work with comission on SIMPLE specification for "prefilling"

**Comment by loicperrin** [comment]
Here are the specification for "prefilling" of outing form:
- Hight diff up : Hight diff up of the first route associated to the outing
- Hight diff down : Hight diff down of the first route associated to the outing
- Elevation max : Elevation max of the first route associated to the outing
- Elevation min : Elevation min of the first route associated to the outing (*)
- Altitude of access point : altitude of the 1st WP with "access" type associated to the first route associated to the outing (*) 

(*) for the 2 last, if a new request which degrades performance is necessary, we can forget these ones

**Comment by brunobesson** [comment]
Glacier gear is now handled (#1357)

**Comment by asaunier** [comment]
> Here are the specification for "prefilling" of outing form:
>
> Hight diff up : Hight diff up of the first route associated to the outing
Hight diff down : Hight diff down of the first route associated to the outing
Elevation max : Elevation max of the first route associated to the outing
Elevation min : Elevation min of the first route associated to the outing (*)
Altitude of access point : altitude of the 1st WP with "access" type associated to the first route associated to the outing (*)

When the first associated route is selected (either by using the association tool in the editing form or when the outing is created starting from the route detail view page), the following data are available among others:
* ``height_diff_up``
* ``elevation_max``

Those 2 attributes could be used to set the default value of the matching fields in the outing editing form, the way it is done to set the default title.

Not available:
* ``height_diff_down``
* ``elevation_min``

Those 2 attributes are not provided. 2 options:
* no default values are provided for those field
* we add them to the list of attributes returned in the list of routes => it will also impact the route advanced search requests and the list of associated routes in a waypoint page or an outing page, perhaps the simple search route results (not sure). It's probably not a big deal because it does not add much data to the responses and don't really impact the SQL requests performances.

> Altitude of access point : altitude of the 1st WP with "access" type associated to the first route associated to the outing

This attribute cannot be retrieved easily (it would imply to get the list of access WP associated to the selected route - which is not trivial). I recommend to skip this.

TODO:
* [ ] add ``height_diff_down`` and ``elevation_min`` attributes to the route listing service (if validated)
* [ ] refactor the outing title default setting to transfer it from https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/documentservice.js#L131-L156 to https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/editing/outingediting.js
* [ ] add default settings for the attributes listed above

**Comment by asaunier** [comment]
PR https://github.com/c2corg/v6_ui/pull/1801 set default values for attributes:

* height_diff_up
* height_diff_down
* elevation_min
* elevation_max

using data from the first associated route.

As for now, no default values are computed using the possibly associated GPS track.
