### ISSUE TITLE
Impossible to associate a WP to a route in its detail view page

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#616]
When creating a route, we can associate a WP to the route in the creation process. But once the route is saved, it is impossible to add a WP to this route in "display mode". The following error message is displayed:
 "Failed to associate document:
invalid association type : association"

**Comment by asaunier** [comment]
This problem is not limited to routes that have just been created. Same problem with routes migrated from v5.

For instance:
* I open this "old" v5 route: http://c2corgv6.demo-camptocamp.com/routes/45168/fr/mont-de-grange-couloir-de-pertuis 
* I try to associate the WP "Pointe des Mattes" http://c2corgv6.demo-camptocamp.com/waypoints/37407/fr/pointe-des-mattes
* when using the association tool, the following request is done:
```
POST http://c2corgv6-api.demo-camptocamp.com/associations
{"parent_document_id":45168,"child_document_id":37407}
```
* response:
```
400 Bad Request
{"status": "error", "errors": [{"description": "invalid association type", "name": "association", "location": "body"}]}
```
* the association change works when editing the route but it does not use the ``associations`` service => problem with that service?

**Comment by tsauerwein** [comment]
I think the association service checks for the [association type](https://github.com/c2corg/v6_common/blob/master/c2corg_common/associations.py). So instead of `{"parent_document_id":45168,"child_document_id":37407}`, you would have to send `{"parent_document_id":37407,"child_document_id":45168}` (`waypoint, route` instead of `route, waypoint`).

**Comment by asaunier** [comment]
I'm not the good person to do this. @ginold has worked on such changes in the past.
