### ISSUE TITLE
Home Page / Feed V6.0

### ISSUE THREAD

**Issue by fjacon** [c2corg/v6_ui#625]
The activity feed will be a combination of:

- **Activities and regions filters**. Filters remove feed elements that do no match. If no filter is set, all recently created documents would be shown => default feed (for anonymous visitors as well).
 * no lang fitler
 * The feed does not advertise creations of new users.
 * For images: a feed item for grouped images upload (not one per uploaded image).
- Followed documents. They add feed elements, even not matching filters. Actually if the user has set no filters, following documents has no effect since the feed elements are shown anyway.

It should be made obvious somewhere that filters are activated: filter icon or on/off button + a button opening the filter settings interface.

**Only users may be followed**

The home page feed only shows:
* documents created by the followed users or outings they have been associated to. _Note: outings should be shown only once even though several followed users are associated._
* documents (including outings) matching the filters.

Relies on https://github.com/c2corg/v6_api/issues/403

**Comment by asaunier** [comment]
For the records, the "old" issue is here https://github.com/c2corg/v6_ui/issues/226

By the way the comment above only describes the activity feed. But the homepage also have a few other components. For instance an introduction text (for unregistered visitors) + image (see the wireframes).

**Comment by asaunier** [comment]
This issue is based upon the ``feed`` services recently added to the API:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/feed.py
* **homepage activity feed for anonymous users**: ``/feed``
https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/feed.py#L23-L58
```
        Request:
            `GET` `/feed[?pl=...][&limit=...][&token=...]`
        Parameters:
            `pl=...` (optional)
            When set only the given locale will be included (if available).
            Otherwise all locales will be returned.
            `limit=...` (optional)
            How many entries should be returned (default: 10).
            The maximum is 50.
            `token=...` (optional)
            The pagination token. When requesting a feed, the response includes
            a `pagination_token`. This token is to be used to request the next
            page.
```
* **homepage activity feed for authenticated users**: ``/personal-feed``
https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/feed.py#L61-L82
```
        Request:
            `GET` `/personal-feed[?pl=...][&limit=...][&token=...]`
        Parameters: See above for '/feed'.
```

The activity feed UI will also be used in the user profile page (see https://github.com/c2corg/v6_ui/issues/335):
https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/feed.py#L85-L112
```
        Request:
            `GET` `/profile-feed?u={user_id}[&pl=...][&limit=...][&token=...]`
        Parameters:
            `u={user_id}` (required)
            The id of the user whose profile feed is requested.
            For the other parameters, see above for '/feed'.
```

We need a directive/controller couple (a bit like the ``advancedSearch`` https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/static/js/search/advancedsearch.js).

The directive will be plugged in the homepage template (in the user profile as well) instead of the current (temporary) "outing advancedSearch" directive:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/index.html#L48
* depending on the user is authenticated or not (or if the directive is used in a user profile), one of the 3 API services listed above will be requested with the adapted parameters
* we need some infinite scrolling support (=> will trigger new API requests with updated ``limit``/``token`` parameters)
* feed items:
 * will be rendered as cards (as in advanced search pages for instance)
 * may be of almost whatever document types (except "users"), mainly outings, but also WP, routes, images (or groups of images), articles etc. => unlike the advanced search pages
 * a bit like in Facebook, those cards may contain metadata such as "user X has been associated to this outing", "user X has created this route", "user X has uploaded thoses images" etc. See also https://docs.google.com/document/d/1i7hcFVTfxwKSM6BaJ55b78l43angMQekr0zYDpGPAZU/edit#heading=h.9x4q3indhygz
* for homepage feeds, the first card should be a kind of button "add an outing" (we don't need it in user profile page - or maybe only when the user see their own profile feed?) [a bit like the new status textarea in Facebook feed]

**Comment by asaunier** [comment]
Something we have to decide: only one column (as in Facebook, Twitter) or several columns (as in Pinterest) in the homepage feed?

I remember that Xavier, our UX expert, told us that for a timeline it's generally more intuitive to have only one column.

**Comment by tsauerwein** [comment]
+1 for a single column

**Comment by ginold** [comment]
Probably it's easier to navigate, but it will leave lots of place on the sides - what could we fill it with?

**Comment by asaunier** [comment]
Do we really need to "fill spaces on the sides"? Look at Twitter for instance.

We could also use wider cards for the feed.

We have to think about the content of those cards. For instance there will probably be metadata such as "@ginold has been associated to an outing" => displayed on the side of the card for instance? On top?
What say the wireframes?

For cards advertising images uploads, there could be several images to show (one "big" and 2 or 3 smaller). A bit like in Facebook?
<img width="495" alt="capture d ecran 2016-10-13 a 00 42 21" src="https://cloud.githubusercontent.com/assets/1192331/19340479/583d3c5e-9129-11e6-9895-494161316f78.png">

This issue will probably have a great impact on the choice of the resized images, see the discussions about the sizes of resized images, for instance https://github.com/c2corg/v6_images/issues/5

**Comment by stef74** [comment]
It is easy to change ?

I prefer to not consult the association on this ergonomic topic, I prefer
wait beta with other people.

If it's easy ... start as simple ... you can improve after.

I prefer multi colonum because on very large screen the rendering is better
... if you use one column all information (include picto need to be on one
line if there is enough space).

2016-10-13 9:43 GMT+02:00 Alex Saunier <notifications@github.com>:

**Comment by asaunier** [comment]
Closing the issue because the related PRs have been merged.
