### ISSUE TITLE
Climbing site WP - Area information display to be changes/checked

### ISSUE THREAD

**Issue by shortoland** [c2corg/v6_ui#706]
WP display ("site d'escalade", "sae"): http://c2corgv6.demo-camptocamp.com/waypoints/735230/fr/orpierre-adrech-face-cachee

"Nombre d'itinéraires" (translated in "Nombre de voies" in the next version) should not be displayed in the "Accès" area I think. Maybe in "Genéral" ... do you confirm ?

![image8](https://cloud.githubusercontent.com/assets/20488365/19182140/ff1010b8-8c71-11e6-8caa-d0cc7b560b9e.png)

**Comment by asaunier** [comment]
> "Nombre d'itinéraires" should not be displayed in the "Accès" area I think.

Indeed

> Maybe in "Genéral"

Makes sense

By the way I see other weird things:
* [ ] min / max heights of routes translated to "altitude min / max" (perhaps the string in the code is "min / max elevation" insteaf of "min / max height"? And the section title is "elevation" / "altitude" instead of "height"
* [ ] do we really need that many different sections? Or at least it's no use repeating the section name in the attribute names. For instance in section "ratings", no need to write "min rating" and "max rating": "min / max" is enough. Or even "6a+ > 7c".
* [ ] "longueur: medium m" does not make sense.
* [ ] info in the "general" section are too heterogenous, this section contains both "general" info such as the elevation and the waypoint type, and more waypoint-specific data such as "rock_type" etc. The latter data should not be in this "general" section but moved to a special section that would contain ratings, heights etc. => those sections should be re-thought. (*)

(*) same thing for all waypoint types or even all document types?

**Comment by shortoland** [comment]
I have changed the translations for "altitude min / max" and "Altitudes"

**Comment by asaunier** [comment]
@desnoes For me this issue should not be labelled as bug: there is no default except that data ordering and grouping is not very optimal. But it's the job of the association to think about how to optimize the page structure.

**Comment by desnoes** [comment]
@stef74 : what is your opinion?

**Comment by desnoes** [comment]
I propose to move the fields 'routes_quantity' and 'best_periods' to the general section.

**Comment by brunobesson** [comment]
@desnoes I rebuilt your PR in another branch (plus some mnior adjustments).
I think we should then close this issue and report missing bits in other, separated issues.
