### ISSUE TITLE
Wrong URL is used for [users] tags

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_ui#774]
The `[users]` tags are replaced with a link pointing to `/users/377` instead of `/profiles/377`. For example on http://c2corgv6.demo-camptocamp.com/articles/121965/en/credits

**Comment by asaunier** [comment]
There are no ``[users]`` tags. The examples you give are actually wikilinks like  ``[[users/123456|Toto]]`` that is transformed to a ``users/123456``, or ``[[summits/123456|Mount Olympus]]`` linking to ``summits/123456``.

So it's rather related to https://github.com/c2corg/v6_ui/issues/644 (v5 > v6 URLs migration/redirection).

I thought first to use ``users/123456`` URLs instead of ``profiles/123456`` but I have eventually decided to changes to "profiles" in order to be consistent with the API. 

Should we close the issue then?

**Comment by tsauerwein** [comment]
> So it's rather related to #644 (v5 > v6 URLs migration/redirection).

Good point about setting up a redirection. But that is for the links that we can not change. In this case, we generate the links from the Wiki tags. So, we can directly generate a good link (instead of a link, that points to a URL that is redirected).

**Comment by asaunier** [comment]
What do you suggest?

That the wikilinks parser https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/format/wikilinks.py when it finds a "users" (or "summits", "huts", etc.) wikilink directly generates a "profiles" or "waypoints" link?

**Comment by asaunier** [comment]
@tsauerwein OK for closing the issue?
It's part of https://github.com/c2corg/v6_api/issues/417
