### ISSUE TITLE
Route creation: Field 'Matériel de sécurité sur glacier' 

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#792]
When creating a route (ski), the field 'Matériel de sécurité sur glacier' appears in the 'Configurations' block (see picture). It should no be in this list.
![field matos glacier](https://cloud.githubusercontent.com/assets/19892089/19689747/b29e5fbc-9ace-11e6-9dbf-465446bd245d.jpg)

**Comment by asaunier** [comment]
That's because the original string (``glacier``) is used for 2 sets of attribute values:
* ``glacier_gear_types`` => https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L298
* ``route_configuration_types`` => https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L310

The translations is shared between those 2 values.
Since the translation should not be the same, the original strings should not be the same in https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py

I suggest to keep https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L310 (because the original string is already relevant)
and change https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L298 to something like ``glacier_safety_gear``.

**Comment by shortoland** [comment]
I have modified the translation according to Alex's remark.

This kind of problem appears many times in the demo website. One word/string shouldn't be used several times. Do you know if there is already an opened ticket for this global problem ?

**Comment by asaunier** [comment]
>  One word/string shouldn't be used several times. Do you know if there is already an opened ticket for this global problem ?

I don't think so. Feel free to create one and list the conflicts you have found.
Perhaps it's related to https://github.com/c2corg/v6_ui/issues/705 ?

**Comment by shortoland** [comment]
@asaunier That's it.

**Comment by asaunier** [comment]
Closing because transfered to https://github.com/c2corg/v6_ui/issues/705#issuecomment-256283109
