### ISSUE TITLE
Problems with WP

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_ui#825]
Here are some problems with WP:
- [ ] the V5 field "Accès routier" should be migrated into the V6 field "Abstract" (which should be renamed "Acces routier" in case of WP = Access)
- [ ] the V6 field "Acces" should be renamed "Acces TC" (OK if we can do it in Transifex, but please check that it is not a common name used elsewhere)
- [ ] the field "Type de transport en commun" should be displayed only if field "Accessibilite en transport en commun" is different from null and "no service" and diplayed after it
- [ ] the field "Type de transport en commun" should not contain the field "remontée mécanique"
- [ ] ~~to georef the WP on the map, it would be easier if we can recenter the map on a city (as for the map in Topoguide page)~~ see #834
- [ ] for "produits locaux" WP, the field "Heures d'ouverture" should have the same name in display mode as in edition mode
- [ ] globally for several WP, some fields have not the same name in display mode as in edition mode (and probably this cannot be fixed with Transifex)
- [ ] for "produits locaux" WP, in edition mode, the title "Transport & Accès" should be suppressed (it does not contain anything)

**Comment by asaunier** [comment]
>  the V5 field "Accès routier" should be migrated into the V6 field "Abstract" (which should be renamed "Acces routier" in case of WP = Access)

That does not sound very relevant to me. The "abstract" attribute should be used for... abstracts, not access descriptions.

V5's "Accès routier" is actually the "description" attribute. In v6 it remains in the same "description" attribute (with the accommodation info): https://github.com/c2corg/v6_api/blob/master/c2corg_api/scripts/migration/documents/waypoints/parking.py#L84-L85

> the V6 field "Acces" should be renamed "Acces TC" (OK if we can do it in Transifex, but please check that it is not a common name used elsewhere)

Renaming the attribute title in Transifex will not work because the attribute is used for describing the public transportation way for "accesses" and the pedestrian way for "huts":
https://github.com/c2corg/v6_api/blob/master/c2corg_api/scripts/migration/documents/waypoints/parking.py#L87
https://github.com/c2corg/v6_api/blob/master/c2corg_api/scripts/migration/documents/waypoints/huts.py#L94

> the field "Type de transport en commun" should not contain the field "remontée mécanique"

"cable_car" is indeed listed as a possible value for public transportations:
https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L70

Has it been removed in the meantime from the google sheet?

Please note this value exists in v5:
https://github.com/c2corg/camptocamp.org/blob/master/apps/frontend/config/app.yml.in#L1962
and is migrated to v6:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/scripts/migration/documents/waypoints/parking.py#L111

If this value is dropped in v6, I guess it must be ignored during the migration?

> to georef the WP on the map, it would be easier if we can recenter the map on a city (as for the map in Topoguide page)

I agree but that should be a dedicated issue, see https://github.com/c2corg/v6_ui/issues/834
Anyway it's low prio.

> globally for several WP, some fields have not the same name in display mode as in edition mode (and probably this cannot be fixed with Transifex)

Please list them in this issue.

**Comment by asaunier** [comment]
This issue is related to https://github.com/c2corg/v6_ui/issues/791

**Comment by asaunier** [comment]
Moved to https://github.com/c2corg/v6_ui/issues/791#issuecomment-258194538
Closing.
