### ISSUE TITLE
Problems with outing

### ISSUE THREAD

**Issue by celinestern** [c2corg/v6_ui#826]
Error in terms:
* Évaluation des conditions; quantité et qualité de la neige: service régulier au lieu de bonnes; service réduit au lieu de mauvaises
* closed_hut au lieu de fermé
* Qualité du document: fine au lieu de bon
* Parcours partiel: true au lieu de oui
* Cotation glacier au lieu de état glacier?

Case impossible to select:
* transport en commun

**Comment by HSERGERAERT** [comment]
- Évaluation des conditions; quantité et qualité de la neige: service
   régulier au lieu de bonnes; service réduit au lieu de mauvaises
   - closed_hut au lieu de fermé
   - Qualité du document: fine au lieu de bon
   - Cotation glacier au lieu de état glacier?

These four translations have been corrected in Transiflex.

**Comment by stef74** [comment]
could you please use task list check box ( see on bar menu ) it's more easy to follow ;-)

**Comment by asaunier** [comment]
> Évaluation des conditions; quantité et qualité de la neige: service régulier au lieu de bonnes; service réduit au lieu de mauvaises
closed_hut au lieu de fermé
Qualité du document: fine au lieu de bon
Parcours partiel: true au lieu de oui
Cotation glacier au lieu de état glacier?

All this items have been reported in https://github.com/c2corg/v6_ui/issues/705 and fixed in the mean time either in Transifex or by some changes in the code. The official demo is maybe not up to date, but it's OK in the old demo (which is up to date).

> Case impossible to select: "transport en commun"

Indeed. I also observe this problem.
@ginold could you have a look please?

**Comment by shortoland** [comment]
OK for me. @celinestern , do you confirm ?

**Comment by celinestern** [comment]
OK now for "transport select"

**Comment by asaunier** [comment]
@shortoland @celinestern thanks for the feedback. Closing the issue then.
