### ISSUE TITLE
Username in the UI user menu

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#889]
- [ ] When I'm loggued, the name showed at the top of the page is my loggin (fbunoz) instead of my topoguide name (or forum name, but it must not be the loggin).
- [x] In the account parameters, the topguide and forum names are correct. But when I try to change one of the names, I get an error : 
> Updating account failed:
Error with Discourse : Internal Server Error
- [x] In the forum, the forum name showed is my loggin instead of the forum name.

**Comment by HSERGERAERT** [comment]
@arnaud-morvan 
Hi Arnaud, are you in charge of Discourse ? this ticket should have been registered in the v6_forum list.
We have strong doubts how were build the IDs.
On v5, my ID is "herve74", my name "Hervé Sergeraert" and my forum pseudo "Lutin"
On Discourse, my pseudo becomes herve741 (instead of Lutin), the name is herve74 (instead of "Hervé Sergeraert)

I have no clue how to change them.
Is it a migration issue ?

**Comment by stef74** [comment]
For me we need to create (allready done ?) a specific issue for discourse. On topoguide this point is non blocking for me, I propose to let do for go live ... but none blocking.

**Comment by stef74** [comment]
Feel free to change if your are not agree

**Comment by HSERGERAERT** [comment]
I have created a dedicated issue for Discourse 
https://github.com/c2corg/v6_forum/issues/48

**Comment by jmarcmod** [comment]
J'ajoute que sur mon compte V6, via la page http://www.demov6.camptocamp.org/account, la migration a modifié mon pseudo forum V5 (J.Marc) en JMarcd1 alors que J.Marc est théoriquement compatible discourse...
Comme Bubu, je ne peux pas changer ce pseudo (même message d'erreur) ; et quand je veux le changer en J.Marc, je ne peux même pas cliquer sur "enregistrer", j'ai le panneau d'interdiction, comme si le point était caractère interdit...

**Comment by asaunier** [comment]
>  When I'm loggued, the name showed at the top of the page is my loggin (fbunoz) instead of my topoguide name (or forum name, but it must not be the loggin).

For me it's OK. I think we have discussed it with @tsauerwein and have chosen to keep the login here. Mainly because it is often shorter and is anyway not displayed to the public.

In brief, it's a choice, not an error.
I admit that in the forum that's the "forum_username" that is used, so using the same in the UI would make sense as well.

I think the other points are already fixed See https://github.com/c2corg/v6_forum/issues/48
I have checked them and renamed the issue.

**Comment by desnoes** [comment]
@asaunier @jmarcmod @fbunoz : can we close this issue ?

**Comment by jmarcmod** [comment]
@desnoes : 
Pour le forum tout est OK.
Reste que dans le bouton de compte bleu, en haut à droite des pages topoguide, ce n'est pas l'identifiant qui devrait apparaitre, mais le nom d'utilisateur (= pseudo topoguide).
Pas critique car seul l'utilisateur le voit, mais très déroutant pour les nouveaux, et embêtant si on poste une copie d'écran (l'identifiant étant souvent le vrai nom qu'on veut cacher).
Comme c'est le seul problème résiduel, il serait peut-être opportun de fermer cette issue, et d'en ouvrir une autre juste pour ce point précis ?

**Comment by desnoes** [comment]
@jmarcmod: merci pour les explications. Je laisse l'issue ouverte.
