### ISSUE TITLE
Invalid image url on home feed

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#910]
On the home feed, the image url are invalid in the card : 
```background-image: url(//sos.exo.io/c2corg_demov6_active1479025574_280720615MI.jpg)```
instead of
```background-image: url(//sos.exo.io/c2corg_demov6_active/1479025574_280720615MI.jpg)```

It is not stable : sometime the url is correct, sometime it misses a / , sometime there is 2 slash ( // ) !

**Comment by asaunier** [comment]
@arnaud-morvan It looks like some problem you have reported today, doesn't it?

**Comment by fbunoz** [comment]
An exemple of double // : http://www.demov6.camptocamp.org/images/815757/fr/design-fil-d-activite (in url of the main image)

**Comment by asaunier** [comment]
Could it be related to a trailing / in a config such as https://github.com/c2corg/v6_ui/blob/master/config/demo#L11 ?

**Comment by arnaud-morvan** [comment]
It seems that we need the ending ``/`` for all pages except image detail view. I suggest to correct the image detail view.

**Comment by asaunier** [comment]
@ginold could you have a look, please?

**Comment by ginold** [comment]
I'm not sure to understand: does this problem occur on the feed page within the cards or on the image-view page? Because I can't spot any problems in the feed, whereas I see some issues on the view page.

**Comment by asaunier** [comment]
Yes, that's what @arnaud-morvan has reported just above :P 
The problem is with the detail view pages.
Perhaps some config change has been done in the meantime, which explains why the initial comment seems no longer relevant.

**Comment by ginold** [comment]
Ok...
Very likely due to `${create_image_link(image_url + '/' + image['filename'], 'BI', locale['title'])}` with the additional " / ". But this is odd, because it should not matter if the link is `//sos.exo.io/c2corg_demov6_active/1479225519_119738018BI.jpg` 
or
 `//sos.exo.io/c2corg_demov6_active//////1479225519_119738018BI.jpg`. 

At least this works with 
`http://c2corgv6-images.demo-camptocamp.com/active/1479378652_1628870962BI.jpg`
 and
`http://c2corgv6-images.demo-camptocamp.com/active/////1479378652_1628870962BI.jpg`.

But it definetly does not work with the first links. I will create a PR for it now.

**Comment by arnaud-morvan** [comment]
Apache seems to accept multiple slashes, Exoscale S3 storage do not.

**Comment by stef74** [comment]
@fbunoz @shortoland could you test ?

**Comment by stef74** [comment]
@fbunoz @shortoland please test
