### ISSUE TITLE
Route: the field 'orientation' is not displayed

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#921]
The field 'orientation' is not displayed in the route document (see: http://www.demov6.camptocamp.org/routes/822280/fr/tete-de-vauclave-essai-beta-via-ferrata). On the other hand, it is displayed in the corresponding card (see the card from the associated WP: http://www.demov6.camptocamp.org/waypoints/262930/fr/tete-de-vauclave)

**Comment by asaunier** [comment]
Actually the compass graphic is shown - as well as the associated areas - on mobile screens or when the browser screen is made narrow enough. Else the areas are shown over the map. But then it seems the compass is shown nowhere? @ginold do you have an idea?

I wonder if we should not simplify all of this and always show the areas (and the compass) in the standard info block (not on the map)? Ditto for the other data shown in the "post-it" on the map? Anyway we will probably have to do so in the frame of the document organisation fixes https://github.com/c2corg/v6_ui/issues/449 since the map will most likely not spread all over the page (but have the same width than the description block for instance).

**Comment by ginold** [comment]
It's shown on mobile because of the post-it which is visible at all times on desktop and hidden on mobile - the info would be doubled. I can move the orientation to it's own case and move it from the 'location' ?

**Comment by asaunier** [comment]
Up to you. Anyway the orientation cannot be managed in combination with the areas.

**Comment by ginold** [comment]
when I first created it i thought that Location and Orientation are closely related...but it's better to separate. You can check my PR #926

**Comment by stef74** [comment]
@desnoes @shortoland could you test ?

**Comment by desnoes** [comment]
The bug is still there on the demo site.

**Comment by fjacon** [comment]
demo has been updated today.

**Comment by desnoes** [comment]
It has been fixed. I close the issue.
