### ISSUE TITLE
Climbing route: wrong minus sign for global rating

### ISSUE THREAD

**Issue by BorutK** [c2corg/v6_ui#922]
On climbing route documents, the global rating (F, AD−, ... ED+) uses the hyphen-minus character (-) instead of the mathematical symbol minus (−). The advantage of the proper minus sign is that it has the same length as the plus sign.

_(edit)_

**Comment by asaunier** [comment]
> uses the hyphen-minus character (-) instead of the mathematical symbol minus (−)

Are you sure it's not already the case?

When I try to change ``ED-`` in https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L344-L366 to  use ``-`` (hyphen-minus), my diffing tool reports no change at all, whereas it does when changing to ``−``(mathematical symbol minus).

As you can see in https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L344-L366 both ``ED-`` and ``ED+`` have the same length.

Finally I don't really see what's the real gain of having the same length between ``ED-`` and ``ED+`` (if it's not already the case), since you have other ratings with not the same amount of characters (F, ED, etc.) :)

**Comment by ginold** [comment]
I'd say that in fact − and - ``ED-`` and ``ED+``  have different lengths. I can quickly fix it ;)

**Comment by BorutK** [comment]
- Same issue for Ski routes: Labande global grade.
- Same thing for the respective Tooltips.

That is, maybe this issue can hang on. It's really not _such_ an issue.
