### ISSUE TITLE
WP Local product : remove "Transport & Accès" section

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_ui#938]
Fields local.access and local.period are missing.

![local product](https://cloud.githubusercontent.com/assets/19892089/20455031/6be92a52-ae51-11e6-85f5-724ab2274461.jpg)

**Comment by asaunier** [comment]
@desnoes I don't understand this issue: the title and the first comment are not about the same thing.
What should really be done here?

At least it seems the "Transport & Accès" section is no longer shown when adding/editing a local product waypoint.

**Comment by asaunier** [comment]
I have noticed a bug though: ``product_types`` (eg. "bar", "restaurant", "sport_shop" etc.) are not restored correctly in the editing form because the checkboxes for this attribute has no ``ng-checked``:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/edit.html#L360
as for this other checkboxes attribute:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/templates/waypoint/edit.html#L350
(easy to fix)

**Comment by desnoes** [comment]
>At least it seems the "Transport & Accès" section is no longer shown when adding/editing a local product waypoint.

The bug has been fixed.
@asaunier : i let the issue open to fix the bug you've found ?

**Comment by asaunier** [comment]
> i let the issue open to fix the bug you've found ?

OK, I will probably make small PRs this afternoon for easy fixes I have found will reviewing the "bug SA" issues.
