### ISSUE TITLE
Availaibility of images as svg

### ISSUE THREAD

**Issue by mgerbaux** [c2corg/v6_ui#944]
http://www.demov6.camptocamp.org/images/822354/fr/essai-svg-2

- when uploaded, svg images are transformed in png (with too much large weight)
- on the image document page, it seems not possible to download the svg source (which is quite important for collaborative work).

More over, we should be Sure that V5 svg images are correctly migrated as svg files

**Comment by asaunier** [comment]
> when uploaded, svg images are transformed in png

I have reopened issue https://github.com/c2corg/v6_images/issues/8

> on the image document page, it seems not possible to download the svg source 

It is probably related to the isse above but I wonder if the UI image detail view is correct as well? Showing the rasterized resized BI image is OK but clicking on it should open the original SVG. In addition it would probably make sense to mention somewhere that the original image is an SVG?

**Comment by asaunier** [comment]
I think it's worth studying this issue before golive, at least to figure out what should be done in order to fix it.
For instance do we need a special attribute in the DB/API? See for instance https://github.com/c2corg/v6_api/issues/357 (closed but perhaps we should have not?).
If changes are needed in the DB, it might have to be considered before the migration is done.

**Comment by asaunier** [comment]
I have tagged this issue as blocking because I suspect it might be impacted by the migration. See my question above.

**Comment by asaunier** [comment]
I have investigated a bit:

* when uploading an SVG file, the image backend converts it to PNG (JPEG would make more sense) and returns a response such as
```
{"filename": "1480094158_257053204.png"}
```
=> please note: PNG, not SVG
* when the upload is validated, the API receives this PNG filename.
* the SVG file seems not available on the image backend, only the PNG version.

As a result:
* the API is never informed (by the image backend) that the original image is/was an SVG, it thinks the image is a PNG
* the UI is never informed (by the API) that the current version has an SVG original, thus does not make any link toward the SVG original (which seems to no longer exist anyway)

It's OK that SVG are converted (because we need the resized/cropped versions - not sure it was possible with SVG files?) but:
* rather use JPEG than PNG because they are generally based upon JPEG photos
* the SVG orignal should be preserved by the image backend
* the image backend should let the API know an SVG original is available =>  the image's ``has_svg`` attribute was actually needed => https://github.com/c2corg/v6_api/pull/482 should be reverted
* the API should pass this ``has_svg`` attribute to the UI
* the UI should provide a link to the original SVG image


Migrated SVG?

**Comment by stef74** [comment]
@asaunier When do you think this issue is fixed ?

**Comment by asaunier** [comment]
Work in progress...

**Comment by stef74** [comment]
@mgerbaux could you test ?

**Comment by mgerbaux** [comment]
There seems to be an issue to access to svg migrated from v5 files :

http://www.demov6.camptocamp.org/images/819610/fr/itineraire-direct-entre-le-pas-de-monthieux-et-les-verts → http://sos.exo.io/c2corg_demov6_active/1478423330_1375656693.svg is not valid
so as http://sos.exo.io/c2corg_demov6_active/1479143096_1734573757.svg :
![capture du 2016-12-02 15 19 08](https://cloud.githubusercontent.com/assets/22116605/20837087/bf866714-b8a2-11e6-97bb-79089a25ad49.png)

**Comment by asaunier** [comment]
@arnaud-morvan could it be related to https://github.com/c2corg/v6_images/issues/8 ?

**Comment by arnaud-morvan** [comment]
This error append when the file do not exists in the S3 bucket.
I've manually migrated this file (using -k 1479143096_1734573757.svg) and it is now available.
Note that SVG files are not available for the demo, I will run the migration for thoses files right now.

**Comment by asaunier** [comment]
@arnaud-morvan thanks!

@mgerbaux uploading new SVG is OK. Please close the issue if OK for you.
