### ISSUE TITLE
Uncomplete document https URLs are redirected to http instead of https

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_ui#981]
I test the demo using https.
When I clic on a partial url, there is a redirection to the full url. But the redirection changed https to http.
Try with this url : https://www.demov6.camptocamp.org/images/821218
Or with the first lik in the description of this doc : https://www.demov6.camptocamp.org/waypoints/38970/fr/mont-pelvoux-pointe-puiseux
The redirection is also used with the link to the profile in the menu.

**Comment by stef74** [comment]
We probably start in HTTP because some issue with HTTPS (geoname for ex).

**Comment by asaunier** [comment]
By "partial URL", I guess you mean a document URL with no lang and slug, which indeed redirects to the full URL with lang and slug.

Indeed https://www.demov6.camptocamp.org/images/821218 redirects to http://www.demov6.camptocamp.org/images/821218/fr/versant-w-des-pics-de-berlanche-et-du-grand-charnier-d-allevard instead of https://www.demov6.camptocamp.org/images/821218/fr/versant-w-des-pics-de-berlanche-et-du-grand-charnier-d-allevard

There is probably an error (missing scheme?) in https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/views/document.py#L355-L398

**Comment by asaunier** [comment]
The problem is around here:
https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/views/document.py#L356-L369

A ``Location`` header is generated but with a relative path (``location = self.request.route_path``) and most likely the scheme is omitted. We probably have to replace ``self.request.route_path`` by ``self.request.route_url``. If it is not enough, we might have to add a ``_scheme``.

It's pretty hard to test because except the demo we have no https instance available.

**Comment by asaunier** [comment]
It seems PR #1062 has not fixed the problem: the https scheme is still lost when redirecting to the slug URL.

Perhaps ``self.request.scheme`` https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/views/document.py#L349 is not the relevant data because SSL is only used to reach the frontend (haproxy? gunicorn?) and is not propagated to pyramid, ``self.request.scheme``  would then always be "http".

Perhaps we should test if the original scheme is passed through an HTTP header?

**Comment by tsauerwein** [comment]
This information should be passed on in a `X-Forwarded-Proto` header, see http://docs.gunicorn.org/en/stable/deploy.html

> When Nginx is handling SSL it is helpful to pass the protocol information to Gunicorn. Many web frameworks use this information to generate URLs. Without this information, the application may mistakenly generate ‘http’ URLs in ‘https’ responses, leading to mixed content warnings or broken applications. In this case, configure Nginx to pass an appropriate header:
>
> proxy_set_header X-Forwarded-Proto $scheme;

This is for nginx, but this should also be possible with haproxy. @mfournier?

**Comment by asaunier** [comment]
> This information should be passed on in a X-Forwarded-Proto header

See also http://docs.pylonsproject.org/projects/waitress/en/latest/#using-behind-a-reverse-proxy

I have noticed this suggestion at https://groups.google.com/forum/#!topic/pylons-discuss/vw7DSnG98jc
```
[app:main]
filter-with = proxy-prefix

[filter:proxy-prefix]
use = egg:PasteDeploy#prefix
```
we could add to our ``production.ini`` (or ``common.ini``?) file.
@tsauerwein do you think it would work in our case?

We would have to add this config and make sure a ``X-Forwarded-Proto`` header is passed from the proxy.

**Comment by tsauerwein** [comment]
This seems to work correctly on the production site. E.g. https://www.camptocamp.org/waypoints/38970 is redirected to https://www.camptocamp.org/waypoints/38970/fr/mont-pelvoux-pointe-puiseux

**Comment by asaunier** [comment]
> This seems to work correctly on the production site.

Not sure it works because of the changes I did in the redirecting tool though.
I guess there's a global http to https redirection that is configured on the prod.
For instance http://www.camptocamp.org/ automatically redirects to https://www.camptocamp.org/

**Comment by stef74** [comment]
All link are correctly set in https (profil, menu, internal link)
